server:
  port: 7090

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/netdisk?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: hsy031122
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#项目目录
project:
  folder: D:/Data/Project/Netdisk

#日志级别配置
log:
  root:
    level: debug









