server:
  port: 7090
  servlet:
    context-path: /api
    # session过期时间 60M 一个小时
    session:
      timeout: PT60M

spring:
  # 配置文件
  profiles:
    active: local
  mvc:
    # 异常处理
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/netdisk?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: hsy031122
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 发送邮件相关配置
  mail:
    # 配置邮件服务器的地址
    host: smtp.163.com
    # 配置邮件服务器的端口
    port: 465
    # 配置用户的账号
    username: hsy040506@163.com
    # 配置授权码
    password: PIFASGVRTVXTJRNL
    # 配置默认编码
    default-encoding: UTF-8
    properties:
      # SSL 连接配置
      mail:
        smtp:
          socketFactory: javax.net.ssl.SSLSocketFactory
      # 开启 debug，这样方便开发者查看邮件发送日志
      debug: true
    protocol: smtps
  # Redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 2000

#超级管理员id
admin:
  emails: hsy040506@163.com

#是否是开发环境
dev: true

# qq登陆相关
qq:
  app:
    id: 12333
    key: 2222222
  url:
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    access:
      token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    user:
      info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
    redirect: http://easypan.wuhancoder.com/qqlogincalback








